IBX-869: fixed loading of mutations schema
ibexa/graphql pull request #27
Opened 2022-02-22 11:04 UTC by bdunogier

Question | Answer
-- | --
JIRA issue | https://issues.ibexa.co/browse/IBX-869
Type | bugfix
Target Ibexa DXP version | v4.0.x
BC breaks | no

The schema mutation type is set by detecting what files were generated. When https://github.com/ezsystems/ezplatform-graphql/pull/90 was merged, `DomainContentMutation.types.yaml` was renamed to `ItemMutation.types.yaml`, but the `YamlSchemaProvider` that searches for the files was not updated.

2022-02-22 11:05 UTC, konradoboza approved these changes

2022-02-23 13:05 UTC, adamwojs approved these changes

2022-02-23 14:51 UTC, mnocon requested changes
This one fails after https://github.com/ibexa/graphql/pull/26 has been merged.

When I try to execute a mutation like:
```
mutation createFolder {
  createFolder(
    language: eng_GB
    parentLocationId: 2
    input: {
      name: "New Folder"
    }
  ) {
    id
  }
}
```
Then the server response looks like this:
```
{
  "errors": [
    {
      "debugMessage": "Too few arguments to function Ibexa\\GraphQL\\Resolver\\DomainContentMutationResolver::createDomainContent(), 1 passed in /Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Resolver/AbstractProxyResolver.php on line 36 and exactly 4 expected",
      "message": "Internal server Error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createFolder"
      ],
      "trace": [
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Resolver/AbstractProxyResolver.php",
          "line": 36,
          "call": "Ibexa\\GraphQL\\Resolver\\DomainContentMutationResolver::createDomainContent(array(4))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Definition/GraphQLServices.php",
          "line": 34,
          "call": "Overblog\\GraphQLBundle\\Resolver\\AbstractProxyResolver::resolve(array(2))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/var/cache/behat/overblog/graphql-bundle/__definitions__/ItemMutationType.php",
          "line": 136,
          "call": "Overblog\\GraphQLBundle\\Definition\\GraphQLServices::mutation('CreateDomainContent', array(4))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/overblog/graphql-bundle/src/Definition/ArgumentFactory.php",
          "line": 37,
          "call": "Overblog\\GraphQLBundle\\__DEFINITIONS__\\ItemMutationType::Overblog\\GraphQLBundle\\__DEFINITIONS__\\{closure}(null, instance of Overblog\\GraphQLBundle\\Definition\\Argument(3), instance of ArrayObject(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 623,
          "call": "Overblog\\GraphQLBundle\\Definition\\ArgumentFactory::Overblog\\GraphQLBundle\\Definition\\{closure}(null, array(3), instance of ArrayObject(2), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 474,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: ItemMutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 857,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createFolder')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createFolder')"
        },
        {
          "file": "/Users/mareknocon/Desktop/Sites/v3_4/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 859,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
(...)
```

2022-11-15 16:56 UTC, adamwojs commented
@bdunogier Have you addressed @mnocon feedback ?

2022-11-16 08:32 UTC, bdunogier commented
Yes @adamwojs, this is what the 2nd commit does.

2022-11-16 10:03 UTC, mnocon commented
Thanks Bertrand, I've added it to our QA queue

2022-11-22 15:09 UTC, micszo commented
Current status.
Create & Update works.
Delete throws exception.

2022-11-24 09:40 UTC, bdunogier commented
Pushed an extra change that fixes the arguments for the few remaining mutations. I have only tested `deleteContent`, not the other ones (`uploadFiles` and `createToken`).

2022-11-24 14:16 UTC, micszo commented
Current status.

create content OK
update content OK
delete content OK
login / createToken OK
create image / file upload NOK

Exception:
```
"debugMessage": "Call to undefined method Ibexa\\Core\\Repository\\Values\\Content\\Content::getContentInfo()",
      "message": "Internal server Error",
```

2022-11-25 07:55 UTC, bdunogier commented
Note that I’m getting a different error (arguments exception) on `uploadFiles`.

2022-11-25 14:32 UTC, micszo approved these changes
QA Approved on Ibexa Commerce 4.2.4-dev.

There's green light for handling file upload separately, ticket will be created shortly.

2022-11-25 14:50 UTC, micszo commented
New ticket: https://issues.ibexa.co/browse/IBX-4415.

2022-11-26 09:50 UTC, merged