IBX-8536: Removed deprecations in graphql
ibexa/graphql pull request #71
Opened 2024-07-22 14:21 UTC by glye

| :ticket: Issue | IBX-8536 |
|----------------|-----------|

#### Description:
Resolve deprecations in ibexa/graphql

2024-08-21 13:00 UTC, konradoboza approved these changes
Looks okay-ish as long as regressions or E2E GraphQL tests don't expose any missing usage.

2024-08-22 08:30 UTC, glye commented
@konradoboza Am looking into getting all tests running. Is there an up to date doc on installing v5? Am struggling with https://ibexa.atlassian.net/wiki/spaces/ENG/pages/5701714/Installation+via+Flex and dev-master / 5.0.x-dev.

2024-08-22 09:18 UTC, ViniTou requested changes

2024-08-22 09:18 UTC, ViniTou commented on src/lib/Resolver/DomainContentResolver.php
> -    public function resolveDomainFieldValue(Content $content, $fieldDefinitionIdentifier, $args = null)
Please look at https://github.com/ibexa/graphql/blob/main/src/bundle/Resources/config/services/resolvers.yaml#L35
I think this maybe the only case we have here, but we need to check if other removed methods are not used anywhere.

2024-10-23 06:27 UTC, konradoboza approved these changes

2024-10-23 07:29 UTC, tbialcz approved these changes

2024-10-23 11:09 UTC, konradoboza commented
Merging as regressions passed, ref: https://github.com/ibexa/commerce/actions/runs/11477344169/job/31939210332?pr=1088.

2024-10-23 11:09 UTC, merged